// ============================================================
// LockFile.swift
// ARO Package Manager - plugins.lock Management
// ============================================================

import Foundation
import Yams

// MARK: - Locked Plugin

/// A single plugin entry in the lock file
public struct LockedPlugin: Codable, Sendable, Equatable {
    /// Plugin name
    public let name: String

    /// Pinned version string
    public let version: String

    /// Git repository URL
    public let git: String?

    /// Git reference (branch or tag)
    public let ref: String?

    /// Exact commit hash — acts as the reproducible checksum
    public let commit: String?

    public init(
        name: String,
        version: String,
        git: String? = nil,
        ref: String? = nil,
        commit: String? = nil
    ) {
        self.name = name
        self.version = version
        self.git = git
        self.ref = ref
        self.commit = commit
    }
}

// MARK: - Plugins Lock

/// Represents the `plugins.lock` file
///
/// The lock file pins every installed plugin to an exact commit,
/// guaranteeing reproducible builds across machines. It is generated
/// automatically by `aro add` / `aro plugins update` and should be
/// committed to source control.
///
/// ## Format
/// ```yaml
/// # plugins.lock — auto-generated by aro, do not edit manually
/// format-version: 1
/// locked:
///   - name: csv-plugin
///     version: 1.2.0
///     git: "git@github.com:user/plugin.git"
///     ref: "v1.2.0"
///     commit: "abc123def456..."
/// ```
public struct PluginsLock: Codable, Sendable {
    /// Format version for forward compatibility
    public let formatVersion: Int

    /// All locked plugin entries
    public var locked: [LockedPlugin]

    enum CodingKeys: String, CodingKey {
        case formatVersion = "format-version"
        case locked
    }

    public init(locked: [LockedPlugin] = []) {
        self.formatVersion = 1
        self.locked = locked
    }

    // MARK: - File I/O

    /// Load a lock file from disk
    /// - Parameter url: Path to `plugins.lock`
    public static func load(from url: URL) throws -> PluginsLock {
        let contents = try String(contentsOf: url, encoding: .utf8)
        let decoder = YAMLDecoder()
        return try decoder.decode(PluginsLock.self, from: contents)
    }

    /// Write the lock file to disk
    /// - Parameter url: Destination path (typically `<app>/plugins.lock`)
    public func save(to url: URL) throws {
        let encoder = YAMLEncoder()
        let yaml = try encoder.encode(self)
        let content = "# plugins.lock — auto-generated by aro, do not edit manually\n" + yaml
        try content.write(to: url, atomically: true, encoding: .utf8)
    }

    // MARK: - Mutations

    /// Add a new entry or replace an existing one with the same name
    public mutating func upsert(_ plugin: LockedPlugin) {
        if let index = locked.firstIndex(where: { $0.name == plugin.name }) {
            locked[index] = plugin
        } else {
            locked.append(plugin)
        }
    }

    /// Remove a plugin entry by name
    public mutating func remove(name: String) {
        locked.removeAll { $0.name == name }
    }

    /// Look up the locked entry for a plugin
    public func entry(for name: String) -> LockedPlugin? {
        locked.first { $0.name == name }
    }
}

// MARK: - Lock File Errors

/// Failures that concern the lock file itself rather than any one plugin
public enum LockFileError: Error, CustomStringConvertible, Equatable {
    /// `plugins.lock` exists but could not be parsed. The underlying parse
    /// failure is carried as text so the error stays `Equatable` and can be
    /// asserted on in tests.
    case unreadable(path: String, underlying: String)

    public var description: String {
        switch self {
        case .unreadable(let path, let underlying):
            return """
                Cannot read \(path): \(underlying)

                The lock file records the exact commit of every installed plugin. \
                It has been left untouched — fix the file by hand, restore it from \
                version control, or delete it to start a fresh lock.
                """
        }
    }
}

// MARK: - Lock File Manager

/// Thread-safe manager for reading and writing `plugins.lock`
public final class LockFileManager: Sendable {
    private let lockFileURL: URL
    private let nsLock = NSLock()

    /// Initialize with the application directory (lock file lives at `<dir>/plugins.lock`)
    public init(applicationDirectory: URL) {
        self.lockFileURL = applicationDirectory.appendingPathComponent("plugins.lock")
    }

    // MARK: - Public API

    /// The URL of the lock file
    public var url: URL { lockFileURL }

    /// Whether the lock file exists on disk
    public var exists: Bool {
        FileManager.default.fileExists(atPath: lockFileURL.path)
    }

    /// Load the current lock file.
    ///
    /// A *missing* lock file is an empty lock — that is how the first
    /// `aro add` in a fresh application starts. A lock file that is
    /// present but will not parse is an error, and deliberately not the
    /// same thing: every caller of this method goes on to `save()` the
    /// result, so answering "empty" for an unreadable file silently
    /// rewrote the user's `plugins.lock` with a single entry and threw
    /// away every other plugin's pinned commit. A YAML typo in a
    /// committed lock file cost the whole file on the next install.
    ///
    /// Refusing leaves the damaged file exactly as it is, so the user can
    /// fix the typo (or `git checkout` it) and keep their pins.
    public func load() throws -> PluginsLock {
        guard exists else { return PluginsLock() }
        do {
            return try PluginsLock.load(from: lockFileURL)
        } catch {
            throw LockFileError.unreadable(path: lockFileURL.path, underlying: "\(error)")
        }
    }

    /// Upsert a plugin entry and persist the lock file
    public func upsert(_ plugin: LockedPlugin) throws {
        nsLock.lock()
        defer { nsLock.unlock() }
        var lock = try load()
        lock.upsert(plugin)
        try lock.save(to: lockFileURL)
    }

    /// Remove a plugin entry and persist the lock file
    public func remove(name: String) throws {
        nsLock.lock()
        defer { nsLock.unlock() }
        var lock = try load()
        lock.remove(name: name)
        // Remove the file if no plugins remain
        if lock.locked.isEmpty {
            try? FileManager.default.removeItem(at: lockFileURL)
        } else {
            try lock.save(to: lockFileURL)
        }
    }

    /// Verify that every entry in the lock file still matches its installed commit.
    /// - Parameter pluginsDirectory: The `Plugins/` directory
    /// - Returns: List of mismatched plugin names
    public func verify(pluginsDirectory: URL) throws -> [String] {
        guard exists else { return [] }
        let lock = try load()
        var mismatches: [String] = []

        for entry in lock.locked {
            let manifestPath = pluginsDirectory
                .appendingPathComponent(entry.name)
                .appendingPathComponent("plugin.yaml")

            guard FileManager.default.fileExists(atPath: manifestPath.path),
                  let manifest = try? PluginManifest.parse(from: manifestPath) else {
                mismatches.append(entry.name)
                continue
            }

            // Compare version and commit if present
            if manifest.version != entry.version {
                mismatches.append(entry.name)
            } else if let lockedCommit = entry.commit,
                      let installedCommit = manifest.source?.commit,
                      installedCommit != lockedCommit {
                mismatches.append(entry.name)
            }
        }

        return mismatches
    }
}
