#!/usr/bin/env python3
"""
29_multimodel_doc_qa.py — QA pairs from the books, wiki and proposals,
generated by TWO local models of different families.

What already existed, and why this is not a duplicate of it: the corpus
holds ~4.7k book-sourced and ~800 proposal-sourced pairs plus ~2k wiki
pairs — all generated by ONE model (Qwen3-Coder-30B-4bit), so every pair
carries that single model's blind spots and phrasings. This script sweeps
the same documentation with two models from different families and merges
what survives validation, with per-section coverage accounting so "every
aspect that is written down" is a measurable claim instead of a hope.

Models (both already on disk, chosen for family diversity):
    A: lmstudio-community/Mistral-Small-3.2-24B-Instruct-2506-MLX-8bit
    B: lmstudio-community/Qwen3.6-27B-MLX-8bit  (local LM Studio path)
Override with --models. Loaded one at a time; ~30 GB peak each.

Inputs:
    Book/*/*.md                 (12 books, versioned in this repo)
    Proposals/ARO-*.md          (the authoritative specs)
    data/wiki/*.md              (cloned from the GitHub wiki on first run)

Gates — a pair is saved only if ALL hold:
    * parses out of the model's JSON answer with non-empty Q and A;
    * every ```aro``` block in the answer passes `aro check` (auto-wrapped
      when it is a bare statement) — documentation-shaped hallucinations
      die here;
    * not a near-duplicate (token-Jaccard 0.9) of anything this run or of
      an existing corpus instruction from the same source family.

Coverage: data/29_doc_qa/coverage.json records, per document, how many
sections produced surviving pairs from which model. Sections that yielded
nothing are listed by name — the TODO list for "every aspect".

Usage:
    python3 29_multimodel_doc_qa.py --limit 4          # smoke run
    python3 29_multimodel_doc_qa.py --corpus proposals # one corpus
    python3 29_multimodel_doc_qa.py                    # the full sweep
    python3 29_multimodel_doc_qa.py --save             # ...and save pairs

Without --save nothing is written to the pairs corpus — generation is
expensive and reviewable output lands in data/29_doc_qa/generated.jsonl
first, so a bad run can be inspected and discarded instead of cleaned.
Idempotent on save via clean_notebook_pairs('NB29_docqa').

RESUMABLE: survivors are appended to generated.jsonl as they happen, and
progress.jsonl records every (model, section) already processed. Killing
the run costs at most the section in flight; restarting with the same
arguments skips finished work. A full sweep is ~26-44h — launch it with
run_29_full_sweep.sh, which adds caffeinate + nohup + a log.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

# config.aro_check_snippet invokes bare `aro` from PATH; an installed binary
# can be older than the checker fixes this data depends on. Put the repo's
# own build first so validation always matches the code in this checkout.
_REPO = Path(__file__).resolve().parents[2]
for _cfg in ('release', 'debug'):
    _bin = _REPO / '.build' / _cfg
    if (_bin / 'aro').exists():
        os.environ['PATH'] = f"{_bin}:{os.environ.get('PATH', '')}"
        break

sys.path.insert(0, str(Path(__file__).parent))
from config import (  # noqa: E402
    TRAIN_ROOT, DATA_ROOT, WIKI_DIR,
    save_notebook_pairs, clean_notebook_pairs,
    aro_check_snippet, auto_wrap_aro, extract_aro_blocks,
    NearDuplicateIndex, PAIRS_FILE,
)

NOTEBOOK_TAG = 'NB29_docqa'
OUT_DIR = DATA_ROOT / '29_doc_qa'
REPO = Path(__file__).resolve().parents[2]
WIKI_REMOTE = 'https://github.com/arolang/aro.wiki.git'

DEFAULT_MODELS = [
    'lmstudio-community/Mistral-Small-3.2-24B-Instruct-2506-MLX-8bit',
    str(Path.home() / '.lmstudio/models/lmstudio-community/Qwen3.6-27B-MLX-8bit'),
]

GEN_PROMPT = """You are building training data for a coding assistant for the ARO \
programming language. Below is one section of ARO's official documentation.

Write 3 question/answer pairs that this section answers. Rules:
- Questions a real ARO programmer would ask; vary the angle (how do I, why
  does, what happens when, which syntax).
- Answers must come from the section — no invented syntax, actions or
  qualifiers. Quote ARO statements exactly as the section spells them.
- When the answer benefits from code, include ONE short ```aro block.
- Output ONLY a JSON array: [{"q": "...", "a": "..."}, ...]

# Section: {title}

{body}
"""


# ── inputs ───────────────────────────────────────────────────────────────────

def ensure_wiki() -> Path:
    if WIKI_DIR.exists() and any(WIKI_DIR.glob('*.md')):
        return WIKI_DIR
    print(f'cloning wiki into {WIKI_DIR} ...')
    subprocess.run(['git', 'clone', '--depth', '1', WIKI_REMOTE, str(WIKI_DIR)],
                   check=True, capture_output=True, text=True)
    return WIKI_DIR


def collect_documents(corpus: str) -> list[tuple[str, str, Path]]:
    """(source_kind, source_ref, path) for every input document."""
    docs = []
    if corpus in ('all', 'book'):
        for p in sorted((REPO / 'Book').rglob('*.md')):
            if 'output' in p.parts:
                continue
            docs.append(('book_qa', f'book:{p.relative_to(REPO)}', p))
    if corpus in ('all', 'proposals'):
        for p in sorted((REPO / 'Proposals').glob('ARO-*.md')):
            docs.append(('proposal', f'proposal:{p.stem}', p))
    if corpus in ('all', 'wiki'):
        wiki = ensure_wiki()
        for p in sorted(wiki.glob('*.md')):
            docs.append(('wiki', f'wiki:{p.stem}', p))
    return docs


def split_sections(text: str) -> list[tuple[str, str]]:
    """(title, body) per `##` section, sized for one prompt."""
    parts = re.split(r'^(#{1,3} .+)$', text, flags=re.M)
    sections, title = [], 'Introduction'
    for chunk in parts:
        if re.match(r'^#{1,3} ', chunk):
            title = chunk.lstrip('#').strip()
        else:
            body = chunk.strip()
            if 300 <= len(body) <= 6000:
                sections.append((title, body))
            elif len(body) > 6000:
                for i in range(0, len(body), 5000):
                    sections.append((title, body[i:i + 5000]))
    return sections


# ── generation ───────────────────────────────────────────────────────────────

def load_model(model_id: str):
    from mlx_lm import load
    print(f'loading {model_id} ...')
    # Mistral tokenizers ship a broken pre-tokenizer regex; transformers
    # warns that tokenization is incorrect unless this flag is set. Wrong
    # tokenization would quietly degrade every pair the model generates.
    config = {'fix_mistral_regex': True} if 'mistral' in model_id.lower() else None
    return load(model_id, tokenizer_config=config)


def generate_pairs(model, tokenizer, title: str, body: str) -> list[dict]:
    from mlx_lm import generate
    from mlx_lm.sample_utils import make_sampler

    prompt = GEN_PROMPT.replace('{title}', title).replace('{body}', body)
    chat = tokenizer.apply_chat_template(
        [{'role': 'user', 'content': prompt}],
        tokenize=False, add_generation_prompt=True)
    text = generate(model, tokenizer, prompt=chat,
                    max_tokens=1200, sampler=make_sampler(temp=0.6),
                    verbose=False)

    match = re.search(r'\[.*\]', text, re.S)
    if not match:
        return []
    try:
        raw = json.loads(match.group(0))
    except json.JSONDecodeError:
        return []
    return [p for p in raw
            if isinstance(p, dict)
            and isinstance(p.get('q'), str) and p['q'].strip()
            and isinstance(p.get('a'), str) and p['a'].strip()]


def code_is_valid(answer: str) -> bool:
    """Every ```aro block must survive `aro check` — hallucination gate."""
    for block in extract_aro_blocks(answer) or []:
        wrapped, _ = auto_wrap_aro(block)
        if wrapped is None:
            continue          # meta/template content, nothing checkable
        passed, _ = aro_check_snippet(wrapped)
        if passed is False:
            return False      # None (no binary) is handled by the caller
    return True


def existing_instructions() -> NearDuplicateIndex:
    """Seed the dedup index with corpus instructions from doc sources, so a
    second model does not re-save what the first sweep already taught."""
    index = NearDuplicateIndex(threshold=0.9)
    if not PAIRS_FILE.exists():
        return index
    for line in open(PAIRS_FILE):
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        src = str(d.get('source', ''))
        if any(k in src.lower() for k in ('book', 'wiki', 'proposal')):
            text = d.get('instruction') or ''
            if text:
                index.add(text)
    return index


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--models', nargs='+', default=DEFAULT_MODELS)
    ap.add_argument('--corpus', choices=['all', 'book', 'wiki', 'proposals'],
                    default='all')
    ap.add_argument('--limit', type=int, default=0,
                    help='max sections per corpus (0 = all) — smoke runs')
    ap.add_argument('--save', action='store_true',
                    help='also save surviving pairs to the training corpus')
    args = ap.parse_args()

    # The aro binary must be present and current — pairs with unchecked code
    # are exactly the failure mode this pipeline exists to prevent.
    probe, msg = aro_check_snippet('Log "x" to the <console>.')
    if probe is None:
        sys.exit('no `aro` binary on PATH — build one or `export PATH`. '
                 'Refusing to generate unvalidated pairs.')

    docs = collect_documents(args.corpus)
    sections = []
    for kind, ref, path in docs:
        for title, body in split_sections(path.read_text(errors='replace')):
            sections.append((kind, ref, title, body))
    if args.limit:
        # Spread the limit across corpora rather than truncating head-first.
        per_kind = {}
        limited = []
        for s in sections:
            per_kind.setdefault(s[0], 0)
            if per_kind[s[0]] < args.limit:
                limited.append(s)
                per_kind[s[0]] += 1
        sections = limited
    print(f'{len(docs)} documents → {len(sections)} sections; '
          f'{len(args.models)} models')

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / 'generated.jsonl'
    progress_path = OUT_DIR / 'progress.jsonl'

    # Resume: skip (model, section) pairs already processed, and seed the
    # dedup index with everything already generated so a restart cannot
    # re-save near-duplicates of its own earlier output.
    done = set()
    coverage = {}
    if progress_path.exists():
        for line in open(progress_path):
            try:
                r = json.loads(line)
            except json.JSONDecodeError:
                continue
            done.add((r['model'], r['key']))
            cov = coverage.setdefault(r['key'], {'kind': r['kind'], 'models': {}})
            cov['models'][r['model']] = cov['models'].get(r['model'], 0) + r['kept']
        print(f'resuming: {len(done)} (model, section) pairs already done')

    dedup = existing_instructions()
    if out_path.exists():
        for line in open(out_path):
            try:
                dedup.add(json.loads(line)['instruction'])
            except (json.JSONDecodeError, KeyError):
                continue

    stats = {'generated': 0, 'bad_json': 0, 'bad_code': 0, 'dup': 0}

    for model_id in args.models:
        model_tag = Path(model_id).name
        todo = [s for s in sections
                if (model_tag, f'{s[1]}#{s[2]}') not in done]
        if not todo:
            print(f'{model_tag}: nothing left to do')
            continue
        model, tokenizer = load_model(model_id)
        print(f'{model_tag}: {len(todo)}/{len(sections)} sections to go')
        out_f = open(out_path, 'a')
        prog_f = open(progress_path, 'a')
        for n, (kind, ref, title, body) in enumerate(todo, 1):
            pairs = generate_pairs(model, tokenizer, title, body)
            if not pairs:
                stats['bad_json'] += 1
            key = f'{ref}#{title}'
            cov = coverage.setdefault(key, {'kind': kind, 'models': {}})
            kept = 0
            for p in pairs:
                stats['generated'] += 1
                if not code_is_valid(p['a']):
                    stats['bad_code'] += 1
                    continue
                if dedup.check_and_add(p['q']):
                    stats['dup'] += 1
                    continue
                out_f.write(json.dumps({
                    'instruction': p['q'],
                    'output': p['a'],
                    'source': kind,
                    'task_type': 'syntax_qa',
                    'category': 'doc_qa_multimodel',
                    'doc_ref': ref,
                    'gen_model': model_tag,
                }) + '\n')
                kept += 1
            cov['models'][model_tag] = cov['models'].get(model_tag, 0) + kept
            # One progress line per section, flushed — the resume unit.
            prog_f.write(json.dumps(
                {'model': model_tag, 'key': key, 'kind': kind, 'kept': kept}) + '\n')
            out_f.flush()
            prog_f.flush()
            if n % 25 == 0:
                print(f'  {model_tag}: {n}/{len(todo)} sections '
                      f"(kept so far this run: {stats['generated'] - stats['bad_code'] - stats['dup']})",
                      flush=True)
        out_f.close()
        prog_f.close()
        del model, tokenizer   # release before loading the next one

    survivors = []
    if out_path.exists():
        survivors = [json.loads(line) for line in open(out_path) if line.strip()]

    uncovered = sorted(k for k, v in coverage.items()
                       if not any(v['models'].values()))
    (OUT_DIR / 'coverage.json').write_text(json.dumps({
        'sections': len(coverage),
        'covered': len(coverage) - len(uncovered),
        'uncovered': uncovered,
        'stats': stats,
        'per_section': coverage,
    }, indent=1) + '\n')

    print(f"survivors: {len(survivors)}  "
          f"(generated {stats['generated']}, bad_code {stats['bad_code']}, "
          f"dup {stats['dup']}, empty/bad_json sections {stats['bad_json']})")
    print(f"coverage: {len(coverage) - len(uncovered)}/{len(coverage)} "
          f"sections → {OUT_DIR / 'coverage.json'}")
    print(f"pairs → {out_path}")

    if args.save and survivors:
        removed = clean_notebook_pairs(NOTEBOOK_TAG)
        if removed:
            print(f'replaced {removed} previous pairs')
        written = save_notebook_pairs(NOTEBOOK_TAG, [
            {k: v for k, v in s.items() if k not in ('doc_ref', 'gen_model')}
            | {'category': f"doc_qa|{s['gen_model']}|{s['doc_ref']}"}
            for s in survivors
        ])
        print(f'saved {written} pairs as {NOTEBOOK_TAG}')
    elif args.save:
        print('nothing survived — nothing saved')

    return 0


if __name__ == '__main__':
    sys.exit(main())
