#!/usr/bin/env python3
"""Generate (or verify) FIXTRAIN.md's status tables from the lint rules.

`Train/FIXTRAIN.md` was a point-in-time audit: 83 findings over 6 435 entries
of a `knowledge_pairs.jsonl` that lived on an external volume, with no way to
tell which findings are still possible and which are now impossible. The rules
that make them impossible had meanwhile moved into `config.FIXTRAIN_RULES`, and
nothing mapped an issue to a rule to a test (GitLab #811).

The per-issue sections stay hand-written — they are the audit, and
`fix_training_data.py` turns the same wrong/corrected pairs into training data
— but the two tables at the top are derived:

  * **Rules** — every standing rule, its severity, the issues it covers, and
    the example pair the test suite exercises it with.
  * **Issues** — every `## ISSUE-NNN` heading in this file, the rule that gates
    it, and therefore whether it can come back.

    python3 Train/script/generate_fixtrain.py            # rewrite the tables
    python3 Train/script/generate_fixtrain.py --check    # verify only

`tests/test_fixtrain_examples.py` runs the `--check` and exercises every
example, so a rule added without an example, or an issue left ungated without
saying so, fails the suite.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config  # noqa: E402

FIXTRAIN = Path(__file__).resolve().parent.parent / "FIXTRAIN.md"
BEGIN = "<!-- BEGIN GENERATED FIXTRAIN STATUS -->"
END = "<!-- END GENERATED FIXTRAIN STATUS -->"

ISSUE_HEADING = re.compile(r"^## (ISSUE-(\d+)): (.*)$", re.MULTILINE)
ISSUE_REF = re.compile(r"ISSUE-([\d/]+)")
TEST = "tests/test_fixtrain_examples.py"


def issues_for(rule: dict) -> list[str]:
    """The FIXTRAIN issue ids a rule's message says it covers."""
    found: list[str] = []
    for match in ISSUE_REF.finditer(rule["message"]):
        for part in match.group(1).split("/"):
            if part and f"ISSUE-{part}" not in found:
                found.append(f"ISSUE-{part}")
    return found


def audit_issues(document: str) -> list[tuple[str, str]]:
    """(id, title) for every `## ISSUE-NNN:` section in FIXTRAIN.md."""
    return [(m.group(1), m.group(3)) for m in ISSUE_HEADING.finditer(document)]


def render(document: str) -> str:
    rules = config.FIXTRAIN_RULES
    errors = [r for r in rules if r["severity"] == "error"]
    warns = [r for r in rules if r["severity"] == "warn"]

    gated: dict[str, list[str]] = {}
    for rule in rules:
        for issue in issues_for(rule):
            gated.setdefault(issue, []).append(rule["name"])

    lines = [
        BEGIN,
        "",
        "<!-- Generated by Train/script/generate_fixtrain.py — do not edit by hand. -->",
        "<!-- Regenerate with: python3 Train/script/generate_fixtrain.py -->",
        "",
        "## Status",
        "",
        f"`config.FIXTRAIN_RULES` holds {len(rules)} rules ({len(errors)} error,",
        f"{len(warns)} warning). They run inside `save_notebook_pair()`, so every pair",
        "any notebook emits is linted before it is written: a finding with a rule",
        "cannot re-enter the corpus, a finding without one was corrected in the data",
        "and nothing stops it coming back.",
        "",
        f"Each rule carries the example pair `{TEST}` exercises it with — the wrong",
        "form must trip that rule, the corrected form must trip no rule and pass",
        "`aro check`. Most of the wrong forms pass `aro check` — they parse, they are",
        "simply not what the language means — which is why the lint exists at all.",
        "",
        "| Rule | Severity | Covers | Wrong | Corrected |",
        "|------|----------|--------|-------|-----------|",
    ]

    def cell(text: str) -> str:
        return "`" + text.replace("\n", " ⏎ ").replace("|", "\\|") + "`"

    for rule in rules:
        covers = ", ".join(issues_for(rule)) or "— (GitLab #486)"
        lines.append(
            f"| `{rule['name']}` | {rule['severity']} | {covers} | "
            f"{cell(rule.get('wrong', ''))} | {cell(rule.get('corrected', ''))} |"
        )

    issues = audit_issues(document)
    lines += [
        "",
        "### Issue → rule → status",
        "",
        f"The {len(issues)} findings below, and what became of each.",
        "",
        "| Issue | Gated by | Status | Test |",
        "|-------|----------|--------|------|",
    ]
    for issue, _title in issues:
        rule_names = gated.get(issue, [])
        if rule_names:
            names = ", ".join(f"`{name}`" for name in rule_names)
            lines.append(f"| {issue} | {names} | cannot re-enter | `{TEST}` |")
        else:
            lines.append(f"| {issue} | — | corrected in data only | — |")

    ungated = sum(1 for issue, _ in issues if issue not in gated)
    lines += [
        "",
        f"{len(issues) - ungated} of {len(issues)} findings are gated by a rule; "
        f"{ungated} were corrected in the data and have no standing rule.",
        "",
        END,
    ]
    return "\n".join(lines)


def rewrite(document: str) -> str:
    if BEGIN not in document or END not in document:
        raise SystemExit(f"error: {FIXTRAIN} is missing the {BEGIN} / {END} markers")
    head = document[: document.index(BEGIN)]
    tail = document[document.index(END) + len(END) :]
    return head + render(document) + tail


def check() -> list[str]:
    """Problems a caller (the test suite) should report, empty when current."""
    document = FIXTRAIN.read_text(encoding="utf-8")
    problems = [
        f"rule {rule['name']} has no {key} example"
        for rule in config.FIXTRAIN_RULES
        for key in ("wrong", "corrected")
        if not rule.get(key)
    ]
    if rewrite(document) != document:
        problems.append(f"{FIXTRAIN.name}'s generated status tables are out of date")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without rewriting")
    args = parser.parse_args()

    if args.check:
        problems = check()
        if problems:
            print(
                "error: FIXTRAIN.md and the lint rules disagree:\n"
                + "".join(f"    {problem}\n" for problem in problems)
                + "  Regenerate with: python3 Train/script/generate_fixtrain.py"
            )
            return 1
        print(f"FIXTRAIN.md is up to date: {len(config.FIXTRAIN_RULES)} rules.")
        return 0

    document = FIXTRAIN.read_text(encoding="utf-8")
    updated = rewrite(document)
    if updated == document:
        print("FIXTRAIN.md is already up to date.")
        return 0
    FIXTRAIN.write_text(updated, encoding="utf-8")
    print(f"Updated FIXTRAIN.md: {len(config.FIXTRAIN_RULES)} rules.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
