// ============================================================
// AROXPCProtocol.swift
// SOLARO ↔ XPC service wire format (#282 phase 3)
// ============================================================
//
// Shared types between SOLARO and the out-of-process
// AROXPCService. Kept as plain Codable structs so the protocol
// is inspectable from the outside (XCTAttachment debug dumps,
// release-time tooling) and the on-wire shape is independent of
// the in-memory PauseInfo / TimeTravelRecord types — those can
// evolve independently as long as the conversion functions stay
// honest.
//
// The runtime ABI is one request enum from SOLARO to the
// service and one event enum from the service to SOLARO. Every
// message carries a `correlationID` so concurrent run sessions
// don't get tangled (today we only run one at a time, but the
// hook lands cheaply now and isn't free to add later).

import Foundation

/// Protocol version. Bumped any time a case is added / removed
/// or any field changes shape. SOLARO refuses to talk to a
/// service reporting a different version on the handshake.
public enum AROXPCProtocolVersion {
    public static let current: Int = 1
}

/// Initial handshake. Service answers with its own version +
/// build stamp so the client can refuse a mismatch instead of
/// hanging on the first run command.
public struct AROXPCHandshakeReply: Codable, Sendable {
    public let protocolVersion: Int
    public let serviceVersion: String
    public let pid: Int32
    public init(protocolVersion: Int, serviceVersion: String, pid: Int32) {
        self.protocolVersion = protocolVersion
        self.serviceVersion = serviceVersion
        self.pid = pid
    }
}

/// One unit of work the client asks the service to perform.
/// `runID` is generated by the client and echoed back in every
/// event for this run so out-of-order delivery (or future
/// multi-run support) stays unambiguous.
public enum AROXPCRequest: Codable, Sendable {
    case handshake
    case run(runID: String, projectPath: String,
             entryPoint: String, embeddedConsole: Bool)
    case stop(runID: String)
    case stepContinue(runID: String)
    case stepOver(runID: String)
    case stepIn(runID: String)
    case stepOut(runID: String)
}

/// One unit of work the service ships back across the boundary.
/// Every event is timestamped with the runtime's seconds-since-
/// startup so the client can render relative timing.
public enum AROXPCEvent: Codable, Sendable {
    case ready(handshake: AROXPCHandshakeReply)
    case started(runID: String)
    case pause(runID: String, record: AROXPCPauseRecord)
    /// Batched form of `pause` (#282 phase 3 — wire batching).
    /// Service buffers per-checkpoint records over a short
    /// window (~1 ms) and ships them in one frame so a hot
    /// statement loop costs one syscall + one decode per N
    /// records instead of per record.
    case pauseBatch(runID: String, records: [AROXPCPauseRecord])
    case consoleOutput(runID: String, line: String, isError: Bool)
    case log(runID: String, message: String)
    case ended(runID: String, error: String?)
}

/// Wire form of a pause record. Mirrors the fields SOLARO's
/// `TimeTravelRecord` consumes — kept as a plain Codable so the
/// JSON-able shape can be archived for debugging and bumped
/// independently of the in-memory type.
public struct AROXPCPauseRecord: Codable, Sendable {
    public let time: TimeInterval
    public let kind: Kind
    public let featureSet: String?
    public let file: String?
    public let line: Int?
    public let column: Int?
    public let statement: String?
    public let verb: String?
    public let reason: String?
    public let symbols: [Symbol]
    public let metrics: Metrics?

    public enum Kind: String, Codable, Sendable {
        case pause, error, event, breakpoint
    }

    public struct Symbol: Codable, Sendable {
        public let name: String
        public let typeName: String
        public let value: String
        public init(name: String, typeName: String, value: String) {
            self.name = name
            self.typeName = typeName
            self.value = value
        }
    }

    public struct Metrics: Codable, Sendable {
        public let elapsedNanos: UInt64
        public let residentMemoryBytes: UInt64
        public init(elapsedNanos: UInt64, residentMemoryBytes: UInt64) {
            self.elapsedNanos = elapsedNanos
            self.residentMemoryBytes = residentMemoryBytes
        }
    }

    public init(time: TimeInterval, kind: Kind, featureSet: String?,
                file: String?, line: Int?, column: Int?,
                statement: String?, verb: String?, reason: String?,
                symbols: [Symbol], metrics: Metrics?) {
        self.time = time
        self.kind = kind
        self.featureSet = featureSet
        self.file = file
        self.line = line
        self.column = column
        self.statement = statement
        self.verb = verb
        self.reason = reason
        self.symbols = symbols
        self.metrics = metrics
    }
}

/// Length-prefixed framing helpers (#282 phase 3). The XPC
/// service and the SOLARO proxy both speak a stream of
/// `[4-byte big-endian length][JSON payload]` frames so a chunky
/// pause record doesn't get spliced across multiple read calls
/// and a tiny event doesn't get glued to the next one.
public enum AROXPCFraming {

    public static func encode<T: Encodable>(_ value: T) throws -> Data {
        let payload = try JSONEncoder().encode(value)
        var header = UInt32(payload.count).bigEndian
        var data = Data(bytes: &header, count: 4)
        data.append(payload)
        return data
    }

    /// Pulls one frame off the front of `buffer`, returning the
    /// decoded payload and trimming the consumed bytes from the
    /// buffer. Returns nil when there isn't a full frame yet —
    /// the caller keeps reading and retries.
    public static func nextPayload(in buffer: inout Data) -> Data? {
        guard buffer.count >= 4 else { return nil }
        let header = buffer.prefix(4).withUnsafeBytes { ptr in
            ptr.loadUnaligned(as: UInt32.self)
        }
        let length = Int(UInt32(bigEndian: header))
        guard buffer.count >= 4 + length else { return nil }
        let payload = buffer.subdata(in: 4..<(4 + length))
        buffer.removeFirst(4 + length)
        return payload
    }
}
