// ============================================================
// NativeMLXBackend.swift
// AROAsk - native in-process LLM inference via MLX Swift
// ============================================================
//
// Runs the model directly on Apple Silicon GPU — no Python, no subprocess,
// no HTTP server. This is the preferred backend when running on macOS.

import Foundation
import MLXLLM
import MLXLMCommon
import Tokenizers

/// Bridges a swift-transformers `Tokenizer` to the MLXLMCommon `Tokenizer` protocol.
/// This is the same adapter generated by the `#adaptHuggingFaceTokenizer` macro,
/// inlined here to avoid the macro dependency.
private struct TokenizerBridge: MLXLMCommon.Tokenizer, @unchecked Sendable {
    private let upstream: any Tokenizers.Tokenizer

    init(_ upstream: any Tokenizers.Tokenizer) {
        self.upstream = upstream
    }

    func encode(text: String, addSpecialTokens: Bool) -> [Int] {
        upstream.encode(text: text, addSpecialTokens: addSpecialTokens)
    }

    func decode(tokenIds: [Int], skipSpecialTokens: Bool) -> String {
        upstream.decode(tokens: tokenIds, skipSpecialTokens: skipSpecialTokens)
    }

    func convertTokenToId(_ token: String) -> Int? {
        upstream.convertTokenToId(token)
    }

    func convertIdToToken(_ id: Int) -> String? {
        upstream.convertIdToToken(id)
    }

    var bosToken: String? { upstream.bosToken }
    var eosToken: String? { upstream.eosToken }
    var unknownToken: String? { upstream.unknownToken }

    func applyChatTemplate(
        messages: [[String: any Sendable]],
        tools: [[String: any Sendable]]?,
        additionalContext: [String: any Sendable]?
    ) throws -> [Int] {
        // Convert [[String: any Sendable]] → [[String: String]] for swift-transformers
        let stringMessages: [[String: String]] = messages.map { msg in
            var result: [String: String] = [:]
            for (k, v) in msg { result[k] = "\(v)" }
            return result
        }
        // Convert tools to [[String: Any]]
        let anyTools: [[String: Any]]? = tools?.map { tool in
            var result: [String: Any] = [:]
            for (k, v) in tool { result[k] = v }
            return result
        }
        return try upstream.applyChatTemplate(
            messages: stringMessages,
            chatTemplate: nil,
            addGenerationPrompt: true,
            truncation: false,
            maxLength: nil,
            tools: anyTools
        )
    }
}

/// A tokenizer loader that uses swift-transformers `AutoTokenizer`.
private struct HFTokenizerLoader: TokenizerLoader, Sendable {
    func load(from directory: URL) async throws -> any MLXLMCommon.Tokenizer {
        let hfTokenizer = try await AutoTokenizer.from(modelFolder: directory)
        return TokenizerBridge(hfTokenizer)
    }
}

/// Native MLX backend that loads and runs the model in-process using Apple's
/// MLX framework. No Python, no subprocess, no HTTP server.
///
/// The model directory must already be downloaded (managed by `ModelManager`).
public actor NativeMLXBackend: LMBackend {
    public nonisolated let name: String = "mlx-native"
    public nonisolated let modelIdentifier: String
    private let modelDirectory: URL?

    private var container: ModelContainer?

    public init(modelIdentifier: String, modelDirectory: URL? = nil) {
        self.modelIdentifier = modelIdentifier
        self.modelDirectory = modelDirectory
    }

    public func start() async throws {
        if container != nil { return }

        FileHandle.standardError.write(
            Data("  Loading model \(modelIdentifier)...\n".utf8)
        )

        let tokenizerLoader = HFTokenizerLoader()
        let dir: URL

        if let modelDirectory {
            dir = modelDirectory
        } else {
            throw LMBackendError.invalidResponse(
                "No model directory provided. Run `aro ask` to download the model first."
            )
        }

        guard FileManager.default.fileExists(
            atPath: dir.appendingPathComponent("config.json").path
        ) else {
            throw LMBackendError.invalidResponse(
                "Model not found at \(dir.path). Run `aro ask` to download it."
            )
        }

        container = try await LLMModelFactory.shared.loadContainer(
            from: dir,
            using: tokenizerLoader
        )

        FileHandle.standardError.write(Data("  Model loaded.\n".utf8))
    }

    public func stop() async {
        container = nil
    }

    public func chat(request: LMChatRequest) async throws -> LMChatResponse.Choice.Message {
        guard let container else { throw LMBackendError.notStarted }

        // Convert messages to Chat.Message format
        let chatMessages: [Chat.Message] = request.messages.compactMap { msg in
            switch msg.role {
            case "system":    return .system(msg.content ?? "")
            case "user":      return .user(msg.content ?? "")
            case "assistant": return .assistant(msg.content ?? "")
            case "tool":      return .tool(msg.content ?? "")
            default:          return .user(msg.content ?? "")
            }
        }

        // Convert tool definitions to MLXLMCommon.ToolSpec format
        // ToolSpec is [String: any Sendable] — an OpenAI-style function spec dict
        let tools: [MLXLMCommon.ToolSpec]? = request.tools?.map { def in
            [
                "type": "function" as any Sendable,
                "function": [
                    "name": def.function.name,
                    "description": def.function.description,
                    "parameters": convertToDict(def.function.parameters),
                ] as [String: any Sendable] as any Sendable,
            ] as MLXLMCommon.ToolSpec
        }

        // Build generation parameters
        var genParams = GenerateParameters(
            temperature: Float(request.temperature ?? 0.2),
            topP: 0.9
        )
        genParams.maxTokens = 4096

        // Prepare input with chat template and tools
        let userInput = UserInput(
            prompt: .chat(chatMessages),
            tools: tools
        )

        // Prepare input (applies chat template) then generate
        let lmInput = try await container.prepare(input: userInput)
        let stream = try await container.generate(
            input: lmInput,
            parameters: genParams
        )
        var accumulated = ""
        for try await generation in stream {
            switch generation {
            case .chunk(let text):
                accumulated += text
            default:
                break
            }
        }
        let fullText = accumulated

        // Parse tool calls from the generated text
        let detectedToolCalls = parseToolCalls(from: fullText)

        if !detectedToolCalls.isEmpty {
            // Strip tool call markup from the text content
            let cleanedText = stripToolCallMarkup(from: fullText)
            return LMChatResponse.Choice.Message(
                role: "assistant",
                content: cleanedText.isEmpty ? nil : cleanedText,
                toolCalls: detectedToolCalls
            )
        }

        return LMChatResponse.Choice.Message(
            role: "assistant",
            content: fullText,
            toolCalls: nil
        )
    }

    // MARK: - Tool call parsing

    /// Parse Qwen-style tool calls from generated text.
    ///
    /// Qwen models emit tool calls in two possible formats:
    ///
    /// Format 1 (XML tags):
    /// ```
    /// <tool_call>
    /// {"name": "read_file", "arguments": {"path": "main.aro"}}
    /// </tool_call>
    /// ```
    ///
    /// Format 2 (function call notation):
    /// ```
    /// ✿FUNCTION✿: read_file
    /// ✿ARGS✿: {"path": "main.aro"}
    /// ```
    private func parseToolCalls(from text: String) -> [LMToolCall] {
        var calls: [LMToolCall] = []
        var callIndex = 0

        // Format 1: <tool_call>...</tool_call>
        let xmlPattern = #"<tool_call>\s*(\{.*?\})\s*</tool_call>"#
        if let regex = try? NSRegularExpression(pattern: xmlPattern, options: [.dotMatchesLineSeparators]) {
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            for match in regex.matches(in: text, range: range) {
                if let jsonRange = Range(match.range(at: 1), in: text) {
                    let jsonStr = String(text[jsonRange])
                    if let call = parseToolCallJSON(jsonStr, index: callIndex) {
                        calls.append(call)
                        callIndex += 1
                    }
                }
            }
        }

        // Format 2: ✿FUNCTION✿ / ✿ARGS✿
        if calls.isEmpty {
            let funcPattern = #"✿FUNCTION✿:\s*(\S+)\s*\n✿ARGS✿:\s*(\{.*?\})"#
            if let regex = try? NSRegularExpression(pattern: funcPattern, options: [.dotMatchesLineSeparators]) {
                let range = NSRange(text.startIndex..<text.endIndex, in: text)
                for match in regex.matches(in: text, range: range) {
                    if let nameRange = Range(match.range(at: 1), in: text),
                       let argsRange = Range(match.range(at: 2), in: text) {
                        let name = String(text[nameRange])
                        let args = String(text[argsRange])
                        calls.append(LMToolCall(
                            id: "call_\(callIndex)",
                            function: .init(name: name, arguments: args)
                        ))
                        callIndex += 1
                    }
                }
            }
        }

        return calls
    }

    private func parseToolCallJSON(_ json: String, index: Int) -> LMToolCall? {
        // Handle Python-style JSON (single quotes, True/False/None)
        let cleaned = json
            .replacingOccurrences(of: "'", with: "\"")
            .replacingOccurrences(of: "True", with: "true")
            .replacingOccurrences(of: "False", with: "false")
            .replacingOccurrences(of: "None", with: "null")

        guard let data = cleaned.data(using: .utf8),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let name = obj["name"] as? String else {
            return nil
        }

        let arguments: String
        if let args = obj["arguments"] {
            if let argsData = try? JSONSerialization.data(withJSONObject: args),
               let argsStr = String(data: argsData, encoding: .utf8) {
                arguments = argsStr
            } else {
                arguments = "{}"
            }
        } else {
            arguments = "{}"
        }

        return LMToolCall(
            id: "call_\(index)",
            function: .init(name: name, arguments: arguments)
        )
    }

    private func stripToolCallMarkup(from text: String) -> String {
        var result = text
        // Remove <tool_call>...</tool_call> blocks
        if let regex = try? NSRegularExpression(
            pattern: #"<tool_call>.*?</tool_call>"#,
            options: [.dotMatchesLineSeparators]
        ) {
            result = regex.stringByReplacingMatches(
                in: result,
                range: NSRange(result.startIndex..<result.endIndex, in: result),
                withTemplate: ""
            )
        }
        // Remove ✿FUNCTION✿/✿ARGS✿ blocks
        if let regex = try? NSRegularExpression(
            pattern: #"✿FUNCTION✿:.*?(?=\n[^✿]|\z)"#,
            options: [.dotMatchesLineSeparators]
        ) {
            result = regex.stringByReplacingMatches(
                in: result,
                range: NSRange(result.startIndex..<result.endIndex, in: result),
                withTemplate: ""
            )
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - Schema conversion

    /// Convert JSONValue to a plain [String: any Sendable] dictionary for ToolSpec.
    private func convertToDict(_ value: JSONValue) -> any Sendable {
        switch value {
        case .string(let s): return s as any Sendable
        case .number(let n): return n as any Sendable
        case .bool(let b): return b as any Sendable
        case .null: return NSNull() as any Sendable
        case .array(let arr): return arr.map { convertToDict($0) } as any Sendable
        case .object(let obj):
            var dict: [String: any Sendable] = [:]
            for (k, v) in obj { dict[k] = convertToDict(v) }
            return dict as any Sendable
        }
    }
}
