// ============================================================
// NativeMLXBackend.swift
// AROAsk - native in-process LLM inference via MLX Swift
// ============================================================
//
// Runs the model directly on Apple Silicon GPU — no Python, no subprocess,
// no HTTP server. This is the preferred backend when running on macOS.
//
// On Linux, this entire file is compiled out. Linux uses llama-server
// (llama.cpp with CUDA) or a remote OpenAI-compatible endpoint instead.

#if canImport(MLXLLM)

import Foundation
import Darwin
import MLXLLM
import MLXLMCommon
import Tokenizers

/// Bridges a swift-transformers `Tokenizer` to the MLXLMCommon `Tokenizer` protocol.
/// This is the same adapter generated by the `#adaptHuggingFaceTokenizer` macro,
/// inlined here to avoid the macro dependency.
private struct TokenizerBridge: MLXLMCommon.Tokenizer, @unchecked Sendable {
    private let upstream: any Tokenizers.Tokenizer

    init(_ upstream: any Tokenizers.Tokenizer) {
        self.upstream = upstream
    }

    func encode(text: String, addSpecialTokens: Bool) -> [Int] {
        upstream.encode(text: text, addSpecialTokens: addSpecialTokens)
    }

    func decode(tokenIds: [Int], skipSpecialTokens: Bool) -> String {
        upstream.decode(tokens: tokenIds, skipSpecialTokens: skipSpecialTokens)
    }

    func convertTokenToId(_ token: String) -> Int? {
        upstream.convertTokenToId(token)
    }

    func convertIdToToken(_ id: Int) -> String? {
        upstream.convertIdToToken(id)
    }

    var bosToken: String? { upstream.bosToken }
    var eosToken: String? { upstream.eosToken }
    var unknownToken: String? { upstream.unknownToken }

    /// The chat template string, loaded from the model's .jinja file or
    /// falling back to the standard Qwen/ChatML format.
    var chatTemplateOverride: String?

    func applyChatTemplate(
        messages: [[String: any Sendable]],
        tools: [[String: any Sendable]]?,
        additionalContext: [String: any Sendable]?
    ) throws -> [Int] {
        let stringMessages: [[String: String]] = messages.map { msg in
            var result: [String: String] = [:]
            for (k, v) in msg { result[k] = "\(v)" }
            return result
        }
        // swift-transformers 1.3+ types `tools:` as `[ToolSpec]?` where
        // `ToolSpec == [String: any Sendable]` — pass the input as-is.
        let anyTools: [[String: any Sendable]]? = tools

        // Try with the model's built-in template first
        do {
            return try upstream.applyChatTemplate(
                messages: stringMessages,
                chatTemplate: chatTemplateOverride.map { .literal($0) },
                addGenerationPrompt: true,
                truncation: false,
                maxLength: nil,
                tools: anyTools
            )
        } catch {
            // If no chat template, fall back to ChatML format and encode manually
            var prompt = ""
            for msg in stringMessages {
                let role = msg["role"] ?? "user"
                let content = msg["content"] ?? ""
                prompt += "<|im_start|>\(role)\n\(content)<|im_end|>\n"
            }
            prompt += "<|im_start|>assistant\n"
            return upstream.encode(text: prompt)
        }
    }
}

/// A tokenizer loader that uses swift-transformers `AutoTokenizer`.
/// Also reads `chat_template.jinja` if present (Qwen3 models store the
/// template in a separate file rather than inline in tokenizer_config.json).
private struct HFTokenizerLoader: TokenizerLoader, Sendable {
    func load(from directory: URL) async throws -> any MLXLMCommon.Tokenizer {
        let hfTokenizer = try await AutoTokenizer.from(modelFolder: directory)

        // Try to load chat template from .jinja file (Qwen3 convention)
        var chatTemplate: String? = nil
        let jinjaFile = directory.appendingPathComponent("chat_template.jinja")
        if FileManager.default.fileExists(atPath: jinjaFile.path) {
            chatTemplate = try? String(contentsOf: jinjaFile, encoding: .utf8)
        }
        // Also check tokenizer_config.json for inline template
        if chatTemplate == nil {
            let configFile = directory.appendingPathComponent("tokenizer_config.json")
            if let data = try? Data(contentsOf: configFile),
               let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
               let tmpl = json["chat_template"] as? String {
                chatTemplate = tmpl
            }
        }

        var bridge = TokenizerBridge(hfTokenizer)
        bridge.chatTemplateOverride = chatTemplate
        return bridge
    }
}

/// Native MLX backend that loads and runs the model in-process using Apple's
/// MLX framework. No Python, no subprocess, no HTTP server.
///
/// The model directory must already be downloaded (managed by `ModelManager`).
public actor NativeMLXBackend: LMBackend {
    public nonisolated let name: String = "mlx-native"
    public nonisolated let modelIdentifier: String
    private let modelDirectory: URL

    private var container: ModelContainer?

    public init(modelIdentifier: String, modelDirectory: URL) {
        self.modelIdentifier = modelIdentifier
        self.modelDirectory = modelDirectory
    }

    public func start() async throws {
        if container != nil { return }

        // Ensure the MLX Metal shader library is available before any MLX call.
        // SPM doesn't compile .metal files, so we embed the pre-compiled metallib
        // as a resource and extract it to where MLX expects to find it.
        try Self.ensureMetalLib()

        let verbose = ProcessInfo.processInfo.environment["ARO_ASK_VERBOSE"] != nil
        if verbose {
            FileHandle.standardError.write(
                Data("  Loading model \(modelIdentifier)...\n".utf8)
            )
        }

        let tokenizerLoader = HFTokenizerLoader()

        // Use the model directory already downloaded by ModelManager.
        // This avoids a redundant re-download via HuggingFace Hub API and
        // ensures we always load the version ModelManager has on disk.
        container = try await LLMModelFactory.shared.loadContainer(
            from: modelDirectory,
            using: tokenizerLoader
        )

        if verbose {
            FileHandle.standardError.write(Data("  Model loaded.\n".utf8))
        }
    }

    public func stop() async {
        container = nil
    }

    public func chat(request: LMChatRequest) async throws -> LMChatResponse.Choice.Message {
        guard let container else { throw LMBackendError.notStarted }

        // Convert messages to Chat.Message format
        let chatMessages: [Chat.Message] = request.messages.compactMap { msg in
            switch msg.role {
            case "system":    return .system(msg.content ?? "")
            case "user":      return .user(msg.content ?? "")
            case "assistant": return .assistant(msg.content ?? "")
            case "tool":      return .tool(msg.content ?? "")
            default:          return .user(msg.content ?? "")
            }
        }

        // Convert tool definitions to MLXLMCommon.ToolSpec format
        // ToolSpec is [String: any Sendable] — an OpenAI-style function spec dict
        let tools: [MLXLMCommon.ToolSpec]? = request.tools?.map { def in
            [
                "type": "function" as any Sendable,
                "function": [
                    "name": def.function.name,
                    "description": def.function.description,
                    "parameters": convertToDict(def.function.parameters),
                ] as [String: any Sendable] as any Sendable,
            ] as MLXLMCommon.ToolSpec
        }

        // Build generation parameters.
        //
        // Qwen3-Coder runs in "thinking mode" by default: it emits a
        // `<think>...</think>` block of internal reasoning, then the actual
        // answer (or tool call). Code-gen prompts with tools attached can
        // easily burn 2-4k tokens just thinking, and our system prompt +
        // tool schemas already consume ~3k of the prompt budget. 4096 was
        // not enough headroom and the model frequently got cut off mid-
        // `<think>` with no visible output. Qwen3-Coder's context window
        // is 32k+, so 16k of output budget is safe.
        var genParams = GenerateParameters(
            temperature: Float(request.temperature ?? 0.2),
            topP: 0.9
        )
        genParams.maxTokens = 16384

        // Prepare input with chat template and tools
        let userInput = UserInput(
            prompt: .chat(chatMessages),
            tools: tools
        )

        // Prepare input (applies chat template) then generate
        let lmInput = try await container.prepare(input: userInput)
        let stream = try await container.generate(
            input: lmInput,
            parameters: genParams
        )
        var accumulated = ""
        for try await generation in stream {
            switch generation {
            case .chunk(let text):
                accumulated += text
            default:
                break
            }
        }
        // Normalise the missing-space-before-`<` bug the base model bakes
        // into ARO output (mirrors Train/script/config.py).
        let normalized = normalizeAROWhitespace(in: accumulated)

        // Tool-call parsing uses a thinking-stripped local copy so it can't
        // pick up speculative tool calls the model wrote inside its
        // reasoning. The returned `content` keeps the raw `<think>` block —
        // AskSession strips it on the way out, which lets it surface the
        // "model burned its budget thinking" warning when the post-strip
        // text is empty. If we stripped here, AskSession would see empty
        // text with no `<think>` tag and the truncation signal would be
        // lost.
        let textForToolParsing = stripThinking(normalized).text
        let detectedToolCalls = parseToolCalls(from: textForToolParsing)

        let cleanedText = stripToolCallMarkup(from: normalized)
        return LMChatResponse.Choice.Message(
            role: "assistant",
            content: cleanedText.isEmpty ? nil : cleanedText,
            toolCalls: detectedToolCalls.isEmpty ? nil : detectedToolCalls
        )
    }

    /// Insert the missing space before `<lower` that the base model bakes
    /// into ARO output (`Log "x" to the<console>.` → `... to <console>.`).
    /// Canonical ARO always has whitespace before `<` for system objects,
    /// qualifiers and variables, so the regex is unconditionally safe.
    /// Mirrors `Train/script/config.py::_normalize_aro_whitespace` so the
    /// runtime patch and the next training run converge.
    private static let missingSpaceBeforeAngle: NSRegularExpression = {
        // Force-try is fine — the pattern is a compile-time literal.
        try! NSRegularExpression(pattern: #"(\w)<([a-z])"#)
    }()

    private func normalizeAROWhitespace(in text: String) -> String {
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        return Self.missingSpaceBeforeAngle.stringByReplacingMatches(
            in: text, range: range, withTemplate: "$1 <$2"
        )
    }


    // MARK: - Tool call parsing

    /// Parse Qwen-style tool calls from generated text.
    ///
    /// Qwen models emit tool calls in two possible formats:
    ///
    /// Format 1 (XML tags):
    /// ```
    /// <tool_call>
    /// {"name": "read_file", "arguments": {"path": "main.aro"}}
    /// </tool_call>
    /// ```
    ///
    /// Format 2 (function call notation):
    /// ```
    /// ✿FUNCTION✿: read_file
    /// ✿ARGS✿: {"path": "main.aro"}
    /// ```
    private func parseToolCalls(from text: String) -> [LMToolCall] {
        var calls: [LMToolCall] = []
        var callIndex = 0

        // Format 1: <tool_call>...</tool_call>
        let xmlPattern = #"<tool_call>\s*(\{.*?\})\s*</tool_call>"#
        if let regex = try? NSRegularExpression(pattern: xmlPattern, options: [.dotMatchesLineSeparators]) {
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            for match in regex.matches(in: text, range: range) {
                if let jsonRange = Range(match.range(at: 1), in: text) {
                    let jsonStr = String(text[jsonRange])
                    if let call = parseToolCallJSON(jsonStr, index: callIndex) {
                        calls.append(call)
                        callIndex += 1
                    }
                }
            }
        }

        // Format 2: ✿FUNCTION✿ / ✿ARGS✿
        if calls.isEmpty {
            let funcPattern = #"✿FUNCTION✿:\s*(\S+)\s*\n✿ARGS✿:\s*(\{.*?\})"#
            if let regex = try? NSRegularExpression(pattern: funcPattern, options: [.dotMatchesLineSeparators]) {
                let range = NSRange(text.startIndex..<text.endIndex, in: text)
                for match in regex.matches(in: text, range: range) {
                    if let nameRange = Range(match.range(at: 1), in: text),
                       let argsRange = Range(match.range(at: 2), in: text) {
                        let name = String(text[nameRange])
                        let args = String(text[argsRange])
                        calls.append(LMToolCall(
                            id: "call_\(callIndex)",
                            function: .init(name: name, arguments: args)
                        ))
                        callIndex += 1
                    }
                }
            }
        }

        return calls
    }

    private func parseToolCallJSON(_ json: String, index: Int) -> LMToolCall? {
        // Handle Python-style JSON (single quotes, True/False/None)
        let cleaned = json
            .replacingOccurrences(of: "'", with: "\"")
            .replacingOccurrences(of: "True", with: "true")
            .replacingOccurrences(of: "False", with: "false")
            .replacingOccurrences(of: "None", with: "null")

        guard let data = cleaned.data(using: .utf8),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let name = obj["name"] as? String else {
            return nil
        }

        let arguments: String
        if let args = obj["arguments"] {
            if let argsData = try? JSONSerialization.data(withJSONObject: args),
               let argsStr = String(data: argsData, encoding: .utf8) {
                arguments = argsStr
            } else {
                arguments = "{}"
            }
        } else {
            arguments = "{}"
        }

        return LMToolCall(
            id: "call_\(index)",
            function: .init(name: name, arguments: arguments)
        )
    }

    private func stripToolCallMarkup(from text: String) -> String {
        var result = text
        // Remove <tool_call>...</tool_call> blocks
        if let regex = try? NSRegularExpression(
            pattern: #"<tool_call>.*?</tool_call>"#,
            options: [.dotMatchesLineSeparators]
        ) {
            result = regex.stringByReplacingMatches(
                in: result,
                range: NSRange(result.startIndex..<result.endIndex, in: result),
                withTemplate: ""
            )
        }
        // Remove ✿FUNCTION✿/✿ARGS✿ blocks
        if let regex = try? NSRegularExpression(
            pattern: #"✿FUNCTION✿:.*?(?=\n[^✿]|\z)"#,
            options: [.dotMatchesLineSeparators]
        ) {
            result = regex.stringByReplacingMatches(
                in: result,
                range: NSRange(result.startIndex..<result.endIndex, in: result),
                withTemplate: ""
            )
        }
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - Schema conversion

    /// Convert JSONValue to a plain [String: any Sendable] dictionary for ToolSpec.
    private func convertToDict(_ value: JSONValue) -> any Sendable {
        switch value {
        case .string(let s): return s as any Sendable
        case .number(let n): return n as any Sendable
        case .bool(let b): return b as any Sendable
        case .null: return NSNull() as any Sendable
        case .array(let arr): return arr.map { convertToDict($0) } as any Sendable
        case .object(let obj):
            var dict: [String: any Sendable] = [:]
            for (k, v) in obj { dict[k] = convertToDict(v) }
            return dict as any Sendable
        }
    }

    // MARK: - Metal shader library setup

    /// Make sure the Metal shader library is somewhere MLX will actually
    /// load it from.
    ///
    /// MLX's own search (mlx/backend/metal/device.cpp, load_default_library)
    /// only looks *relative to the running binary*: `mlx.metallib`,
    /// `Resources/mlx.metallib`, a `mlx-swift_Cmlx.bundle/default.metallib`
    /// SwiftPM bundle, and a compile-time METAL_PATH. It knows nothing about
    /// ARO's Homebrew share directory or user cache — so merely *finding*
    /// the file there is not enough; MLX would still abort with its raw
    /// "Failed to load the default metallib" C++ error. For those ARO-only
    /// locations we bridge: symlink (or copy) the metallib to
    /// `<binaryDir>/mlx.metallib`, the first place MLX looks.
    ///
    /// Lookup order:
    ///  1. `mlx.metallib` colocated with the binary — MLX-visible
    ///     (dev builds, scp installs, and the Homebrew install path —
    ///     the formula symlinks `bin/mlx.metallib` to `share/aro/mlx.metallib`)
    ///  2. `mlx-swift_Cmlx.bundle/default.metallib` next to the binary —
    ///     MLX-visible (SwiftPM bundle layout, built by tools/build-metallib.sh)
    ///  3. `../share/aro/mlx.metallib` relative to the binary — bridged
    ///     (Homebrew layout directly, in case the `bin/` symlink is absent)
    ///  4. `~/.cache/aro/mlx/mlx.metallib` — bridged (user-populated fallback)
    ///
    /// Throws a clean error if none are present, or if bridging fails
    /// because the binary's directory is not writable.
    private static func ensureMetalLib() throws {
        let fm = FileManager.default
        let binaryDir = currentExecutableURL().deletingLastPathComponent()

        // Locations MLX searches on its own — nothing to do if one exists.
        let mlxVisible = [
            binaryDir.appendingPathComponent("mlx.metallib"),
            binaryDir
                .appendingPathComponent("mlx-swift_Cmlx.bundle")
                .appendingPathComponent("default.metallib"),
            binaryDir
                .appendingPathComponent("Resources/mlx.metallib"),
        ]
        if mlxVisible.contains(where: { fm.fileExists(atPath: $0.path) }) {
            return
        }

        // ARO-only fallback locations — MLX never checks these, so bridge
        // the first one that exists to `<binaryDir>/mlx.metallib`.
        let fallbacks = [
            binaryDir
                .deletingLastPathComponent()
                .appendingPathComponent("share/aro/mlx.metallib"),
            fm.homeDirectoryForCurrentUser
                .appendingPathComponent(".cache/aro/mlx/mlx.metallib"),
        ]
        if let source = fallbacks.first(where: { fm.fileExists(atPath: $0.path) }) {
            let target = binaryDir.appendingPathComponent("mlx.metallib")
            do {
                // Symlink first (cheap, stays current if the source is
                // updated); fall back to a copy for filesystems or
                // sandboxes where symlinks fail.
                try? fm.removeItem(at: target)  // clear a stale broken link
                do {
                    try fm.createSymbolicLink(at: target, withDestinationURL: source)
                } catch {
                    try fm.copyItem(at: source, to: target)
                }
                return
            } catch {
                throw LMBackendError.invalidResponse(
                    """
                    Found the MLX Metal shader library at
                      \(source.path)
                    but could not link it next to the binary at
                      \(target.path)
                    (\(error.localizedDescription)) — MLX only loads the
                    metallib from next to the binary. Copy it there manually:
                      cp "\(source.path)" "\(target.path)"
                    """
                )
            }
        }

        let searched = (mlxVisible + fallbacks).map { "  " + $0.path }.joined(separator: "\n")
        throw LMBackendError.invalidResponse(
            """
            MLX Metal shader library not found. Looked in:
            \(searched)
            Build it with: tools/build-metallib.sh
            then copy the result to one of the paths above.
            """
        )
    }

    /// Absolute, symlink-resolved URL of the running executable.
    ///
    /// `CommandLine.arguments[0]` is whatever the shell handed us — often
    /// just `"aro"` when invoked via $PATH — and `URL(fileURLWithPath:)`
    /// resolves that against the CWD, which silently anchors every search
    /// path to the user's project directory instead of the binary. Ask the
    /// kernel for the actual executable path instead.
    private static func currentExecutableURL() -> URL {
        var size = UInt32(PATH_MAX)
        var buffer = [CChar](repeating: 0, count: Int(size))
        if _NSGetExecutablePath(&buffer, &size) != 0 {
            // Path didn't fit; resize and retry once.
            buffer = [CChar](repeating: 0, count: Int(size))
            guard _NSGetExecutablePath(&buffer, &size) == 0 else {
                return URL(fileURLWithPath: CommandLine.arguments[0])
            }
        }
        let raw = String(cString: buffer)
        return URL(fileURLWithPath: raw).resolvingSymlinksInPath()
    }
}

#endif // canImport(MLXLLM)
