name: Bug Report
description: Report a bug in the ARO Programming Language
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create file with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: ARO Code (if applicable)
      description: The ARO code that triggers the bug
      render: aro

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Parser (AROParser)
        - Runtime (ARORuntime)
        - Compiler (AROCompiler)
        - CLI (aro command)
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ARO Version
      description: Output of `aro --version`
      placeholder: "e.g., 1.0.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
