name: Feature Request
description: Suggest a new feature for ARO
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it enable?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true

  - type: textarea
    id: syntax
    attributes:
      label: Proposed Syntax (if applicable)
      description: What would the ARO code look like?
      render: aro

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Parser (AROParser)
        - Runtime (ARORuntime)
        - Compiler (AROCompiler)
        - CLI (aro command)
        - New Action
        - Language Syntax
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this change break existing ARO code?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this feature
