// ============================================================
// WhereConditionEvaluator.swift
// ARORuntime — where-condition trees at run time (GitLab #498)
// ============================================================
//
// ARO-0018 §2.2 gives where clauses and/or chaining with
// parentheses. The parser builds a `WhereCondition` tree; both
// execution modes flatten it into framework variables:
//
//   single predicate   _where_field_ / _where_op_ / _where_value_
//   compound           _where_tree_  = "and(0,or(1,2))"
//                      _where_field_N_ / _where_op_N_ / _where_value_N_
//
// The single-predicate triple is unchanged from before #498, so
// consumers that only understand one field/op/value pair (repository
// delete, plugin-visible bindings) keep working untouched. Everything
// that filters collections resolves the full tree through this type.

import Foundation
import AROParser

/// A where condition with its value expressions already evaluated,
/// ready to test items against.
public indirect enum ResolvedWhereCondition: Sendable {
    case predicate(field: String, op: String, value: any Sendable)
    case and(ResolvedWhereCondition, ResolvedWhereCondition)
    case or(ResolvedWhereCondition, ResolvedWhereCondition)

    /// Reads the where-condition framework variables bound by
    /// FeatureSetExecutor (interpreter) or ModifierBinder (compiled).
    /// Returns nil when the statement has no where clause.
    public static func resolve(from context: ExecutionContext) -> ResolvedWhereCondition? {
        if let tree = context.resolveAny("_where_tree_") as? String, !tree.isEmpty {
            if let condition = parse(skeleton: tree, context: context) {
                return condition
            }
            // The skeleton is generated by our own compiler/executor, so a
            // parse failure is a bug — and silently returning nil would make
            // Filter pass everything through. Warn per CLAUDE.md convention.
            FileHandle.standardError.write(Data(
                "[WhereCondition] Warning: unparseable _where_tree_ '\(tree)' — where clause ignored\n".utf8))
            return nil
        }
        if let field = context.resolveAny("_where_field_") as? String {
            let op = context.resolveAny("_where_op_") as? String ?? "is"
            return .predicate(field: field, op: op, value: context.resolveAny("_where_value_") ?? "")
        }
        return nil
    }

    /// Tests one collection element against the condition.
    /// A predicate on a field the item does not carry is false —
    /// same rule the single-predicate Filter always applied.
    public func matches(_ item: [String: any Sendable]) -> Bool {
        switch self {
        case .predicate(let field, let op, let value):
            guard let actual = item[field] else { return false }
            return WherePredicateMatcher.matches(actual: actual, op: op, expected: value)
        case .and(let l, let r):
            return l.matches(item) && r.matches(item)
        case .or(let l, let r):
            return l.matches(item) || r.matches(item)
        }
    }

    /// Convenience for heterogeneous collections: non-dictionary
    /// items never match a field predicate.
    public func matchesElement(_ element: any Sendable) -> Bool {
        guard let dict = element as? [String: any Sendable] else { return false }
        return matches(dict)
    }

    // MARK: - Skeleton parsing

    /// Parses "and(0,or(1,2))" back into a tree, resolving each leaf
    /// index against `_where_field_N_` / `_where_op_N_` / `_where_value_N_`.
    private static func parse(skeleton: String, context: ExecutionContext) -> ResolvedWhereCondition? {
        var characters = Array(skeleton)
        var position = 0

        func parseNode() -> ResolvedWhereCondition? {
            func consume(_ prefix: String) -> Bool {
                let chars = Array(prefix)
                guard position + chars.count <= characters.count,
                      Array(characters[position..<position + chars.count]) == chars else { return false }
                position += chars.count
                return true
            }

            let nodeIsAnd: Bool? = consume("and(") ? true : (consume("or(") ? false : nil)
            if let isAnd = nodeIsAnd {
                guard let left = parseNode() else { return nil }
                guard position < characters.count, characters[position] == "," else { return nil }
                position += 1
                guard let right = parseNode() else { return nil }
                guard position < characters.count, characters[position] == ")" else { return nil }
                position += 1
                return isAnd ? .and(left, right) : .or(left, right)
            }

            // Leaf: a run of digits naming a predicate index
            var digits = ""
            while position < characters.count, characters[position].isNumber {
                digits.append(characters[position])
                position += 1
            }
            guard !digits.isEmpty, let index = Int(digits) else { return nil }
            guard let field = context.resolveAny("_where_field_\(index)_") as? String,
                  let op = context.resolveAny("_where_op_\(index)_") as? String else { return nil }
            return .predicate(field: field, op: op, value: context.resolveAny("_where_value_\(index)_") ?? "")
        }

        guard let node = parseNode(), position == characters.count else { return nil }
        return node
    }
}

/// The single-predicate comparison semantics shared by Filter (eager,
/// streaming, compiled) and compound where conditions. Extracted from
/// FilterAction so `and`/`or` trees compare values by exactly the same
/// rules as a lone predicate.
public enum WherePredicateMatcher {
    public static func matches(actual: Any, op: String, expected: any Sendable) -> Bool {
        let actualStr = String(describing: actual)
        let expectedStr = String(describing: expected)

        switch op.lowercased() {
        case "is", "==", "equals":
            return actualStr == expectedStr

        case "is not", "is-not", "!=", "not-equals":
            return actualStr != expectedStr

        case ">", "gt":
            if let actualNum = asDouble(actual), let expectedNum = asDouble(expected) {
                return actualNum > expectedNum
            }
            return actualStr > expectedStr

        case ">=", "gte":
            if let actualNum = asDouble(actual), let expectedNum = asDouble(expected) {
                return actualNum >= expectedNum
            }
            return actualStr >= expectedStr

        case "<", "lt":
            if let actualNum = asDouble(actual), let expectedNum = asDouble(expected) {
                return actualNum < expectedNum
            }
            return actualStr < expectedStr

        case "<=", "lte":
            if let actualNum = asDouble(actual), let expectedNum = asDouble(expected) {
                return actualNum <= expectedNum
            }
            return actualStr <= expectedStr

        // Temporal comparison (GitLab #516). ISO-8601 strings order
        // correctly lexicographically, which is why the string
        // fallback below is not a lie for dates.
        case "before":
            if let actualNum = asDouble(actual), let expectedNum = asDouble(expected) {
                return actualNum < expectedNum
            }
            return actualStr < expectedStr

        case "after":
            if let actualNum = asDouble(actual), let expectedNum = asDouble(expected) {
                return actualNum > expectedNum
            }
            return actualStr > expectedStr

        case "contains":
            return actualStr.contains(expectedStr)

        case "starts-with":
            return actualStr.hasPrefix(expectedStr)

        case "ends-with":
            return actualStr.hasSuffix(expectedStr)

        case "matches":
            // Regex matching
            do {
                let regex = try RegexCache.shared.regex(expectedStr)
                let range = NSRange(actualStr.startIndex..., in: actualStr)
                return regex.firstMatch(in: actualStr, range: range) != nil
            } catch {
                return false
            }

        case "in":
            // Support array values (ARO-0042)
            if let arr = expected as? [any Sendable] {
                return arr.contains { item in
                    areValuesEqual(actual, item)
                }
            }
            // Fallback to comma-separated values
            let values = expectedStr.split(separator: ",").map { String($0).trimmingCharacters(in: .whitespaces) }
            return values.contains(actualStr)

        case "not in", "not-in", "notin":
            // Support array values (ARO-0042)
            if let arr = expected as? [any Sendable] {
                return !arr.contains { item in
                    areValuesEqual(actual, item)
                }
            }
            // Fallback to comma-separated values
            let values = expectedStr.split(separator: ",").map { String($0).trimmingCharacters(in: .whitespaces) }
            return !values.contains(actualStr)

        default:
            return actualStr == expectedStr
        }
    }

    private static func asDouble(_ value: Any) -> Double? {
        if let d = value as? Double { return d }
        if let i = value as? Int { return Double(i) }
        if let f = value as? Float { return Double(f) }
        if let s = value as? String { return Double(s) }
        return nil
    }

    /// Type-safe equality check for set membership operations (ARO-0042)
    private static func areValuesEqual(_ a: Any, _ b: Any) -> Bool {
        // Integer comparison
        if let aInt = a as? Int, let bInt = b as? Int {
            return aInt == bInt
        }
        // Double comparison
        if let aDouble = a as? Double, let bDouble = b as? Double {
            return aDouble == bDouble
        }
        // String comparison
        if let aStr = a as? String, let bStr = b as? String {
            return aStr == bStr
        }
        // Bool comparison
        if let aBool = a as? Bool, let bBool = b as? Bool {
            return aBool == bBool
        }
        // Fallback to string representation for other types
        return String(describing: a) == String(describing: b)
    }
}
