// ============================================================
// LockFileIntegrityTests.swift
// ARO Package Manager Tests — plugins.lock is never silently discarded
// (GitLab #670)
// ============================================================

import Testing
import Foundation
@testable import AROPackageManager

/// `LockFileManager.load()` used to be `(try? PluginsLock.load(…)) ?? PluginsLock()`,
/// which cannot tell "no lock file yet" from "lock file I could not read". Every
/// caller saves the result, so a YAML typo in a committed `plugins.lock` was
/// rewritten into a one-entry file on the next `aro add` and every other pinned
/// commit was gone. These tests pin the distinction: missing is empty, corrupt is
/// an error, and the corrupt file is left byte-for-byte alone.
@Suite("Lock file integrity (#670)")
struct LockFileIntegrityTests {

    /// A lock file that is valid YAML but the wrong shape (`locked` is a number),
    /// and one that is not valid YAML at all. Both must be refused.
    static let corruptLockFiles: [String] = [
        """
        # plugins.lock — auto-generated by aro, do not edit manually
        format-version: 1
        locked: 12
        """,
        """
        # plugins.lock — auto-generated by aro, do not edit manually
        format-version: 1
        locked:
          - name: csv-plugin
            version: "1.2.0
        """,
    ]

    private func withTemporaryDirectory(_ body: (URL) throws -> Void) throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("aro-lock-integrity-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        try body(dir)
    }

    @Test("A missing lock file loads as an empty lock")
    func missingLockFileIsEmpty() throws {
        try withTemporaryDirectory { dir in
            let manager = LockFileManager(applicationDirectory: dir)
            #expect(!manager.exists)
            let lock = try manager.load()
            #expect(lock.locked.isEmpty)
        }
    }

    @Test("A corrupt lock file is an error, not an empty lock", arguments: corruptLockFiles)
    func corruptLockFileThrows(contents: String) throws {
        try withTemporaryDirectory { dir in
            let lockURL = dir.appendingPathComponent("plugins.lock")
            try contents.write(to: lockURL, atomically: true, encoding: .utf8)

            let manager = LockFileManager(applicationDirectory: dir)
            #expect(throws: LockFileError.self) {
                _ = try manager.load()
            }
        }
    }

    @Test("The error names the lock file so the user can find it")
    func errorNamesTheFile() throws {
        try withTemporaryDirectory { dir in
            let lockURL = dir.appendingPathComponent("plugins.lock")
            try Self.corruptLockFiles[0].write(to: lockURL, atomically: true, encoding: .utf8)

            let manager = LockFileManager(applicationDirectory: dir)
            do {
                _ = try manager.load()
                Issue.record("Expected a LockFileError for an unreadable lock file")
            } catch let error as LockFileError {
                #expect(error.description.contains(lockURL.path))
                #expect(error.description.contains("left untouched"))
            }
        }
    }

    @Test("Upsert refuses to overwrite a corrupt lock file")
    func upsertLeavesCorruptFileAlone() throws {
        try withTemporaryDirectory { dir in
            let lockURL = dir.appendingPathComponent("plugins.lock")
            let original = Self.corruptLockFiles[0]
            try original.write(to: lockURL, atomically: true, encoding: .utf8)

            let manager = LockFileManager(applicationDirectory: dir)
            #expect(throws: LockFileError.self) {
                try manager.upsert(LockedPlugin(name: "new-plugin", version: "1.0.0", commit: "abc"))
            }

            // The whole point: the damaged file still holds the user's bytes.
            let after = try String(contentsOf: lockURL, encoding: .utf8)
            #expect(after == original)
        }
    }

    @Test("Remove refuses to overwrite a corrupt lock file")
    func removeLeavesCorruptFileAlone() throws {
        try withTemporaryDirectory { dir in
            let lockURL = dir.appendingPathComponent("plugins.lock")
            let original = Self.corruptLockFiles[1]
            try original.write(to: lockURL, atomically: true, encoding: .utf8)

            let manager = LockFileManager(applicationDirectory: dir)
            #expect(throws: LockFileError.self) {
                try manager.remove(name: "csv-plugin")
            }

            #expect(FileManager.default.fileExists(atPath: lockURL.path))
            let after = try String(contentsOf: lockURL, encoding: .utf8)
            #expect(after == original)
        }
    }

    @Test("A readable lock file still round-trips through upsert")
    func healthyLockFileStillUpserts() throws {
        try withTemporaryDirectory { dir in
            let manager = LockFileManager(applicationDirectory: dir)
            try manager.upsert(LockedPlugin(name: "csv-plugin", version: "1.2.0", commit: "abc123"))
            try manager.upsert(LockedPlugin(name: "json-plugin", version: "2.0.0", commit: "def456"))

            let lock = try manager.load()
            #expect(lock.locked.count == 2)
            #expect(lock.entry(for: "csv-plugin")?.commit == "abc123")
            #expect(lock.entry(for: "json-plugin")?.version == "2.0.0")
        }
    }
}
